version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: restaurant-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=restaurantdb
    volumes:
      - postgres-data-dev:/var/lib/postgresql/data
    networks:
      - restaurant-network-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  restaurant-network-dev:
    driver: bridge

volumes:
  postgres-data-dev: